### ISSUE TITLE
Preliminary design review with Khosmood

### ISSUE THREAD

**Issue by viyengar96** [ggchan0/CPE_350#15]
Power point presentation with:
a. Present needs, specifications, constraints, and deliverables.
b. Present several viable designs, giving	pros	and cons of each.
c. Provide a well-founded estimate of project costs.
d. Outline a project schedule that produces needed deliverables	with	ample time for product.	
validation.
e. Honestly identify	all potential problems or risks, and describe how you plan to deal with them.

**Comment by ggchan0** [comment]
Will be done this Wednesday when we meet with him
