### ISSUE TITLE
Schedule Weekly Meeting/Next Meeting with Khosmood

### ISSUE THREAD

**Issue by bevintang** [ggchan0/CPE_350#4]
We have yet to schedule a weekly meeting with Khasmood. This makes sense since we have not finalized which APIs we will use, but we have to meet with him at least one more time for the **Design Sprint.**

**Comment by ggchan0** [comment]
Khosmood wants to meet us from 2:30 - 4 PM every Tuesday. He wasn't present yesterday, but we should email him to confirm a time. If not, meeting him in person to get an answer would be preferable.

**Comment by ggchan0** [comment]
We have our meeting time set from 3-3:30 on Wednesdays
