### ISSUE TITLE
Complete Project Charter: Project Development

### ISSUE THREAD

**Issue by viyengar96** [ggchan0/CPE_350#7]
Customer Requirements (1/2-1 page) – What are your customer requirements? What
are they looking for in your project? This can be anything from experience, to
functionality, to specific metrics, and should be what you have learned from your client
during the 2+ meetings you’ve had.

Prototypes (1-2 pages) – Document the evolution of your prototypes. How does each
address your customer requirements? What did you learn from them and the feedback
you received from your client?

**Comment by bevintang** [comment]
I got dat good-good Proto on the d-Low, my boi.
